### ISSUE TITLE
Broken url for aaronson credit

### ISSUE THREAD

**Issue by rogergzou** [ex-punctis/not-so-random#3]
people.ischool.berkeley.edu/~nick/aaronson-oracle/ leads to 404 for me. The requested URL /~nick/aaronson-oracle/ was not found on this server.

**Comment by ex-punctis** [comment]
Sorry for responding so late — for some reason github wouldn't send me email notifications on new issues... I've tried clicking the link in various browsers on different machines, and it opened Nick Merrill's oracle demo without trouble. If you still have trouble accessing it, you can the github repository instead: https://github.com/elsehow/aaronson-oracle
